-- db/auditoria.sql
-- Se ejecuta como 10-auditoria.sql, DESPUES de 09-roles.sql: contiene
-- unicamente el REVOKE sobre app_academico, porque ese rol recien existe
-- a partir de 09-roles.sql. La tabla/funcion/triggers de auditoria en si
-- ya se crean en 01-schema.sql (db/schema.sql), que no depende del rol.
--
-- app_academico hereda SELECT/INSERT/UPDATE/DELETE automaticamente por
-- el ALTER DEFAULT PRIVILEGES ya existente (db/roles.sql). Le dejamos
-- SELECT (GET /api/admin/auditoria lee esta tabla via JPA, con este
-- mismo rol) e INSERT (aunque el trigger no lo necesita, corre como
-- postgres via SECURITY DEFINER -- ver V6__auditoria.sql). Le quitamos
-- UPDATE/DELETE: la app nunca debe poder modificar ni borrar filas de
-- auditoria, solo leerlas y dejar que el trigger las inserte.
REVOKE UPDATE, DELETE ON auditoria FROM app_academico;
