-- V6__auditoria.sql
-- (mismo contenido replicado en db/schema.sql y en
-- docker-entrypoint-initdb.d/10-auditoria.sql, ver docker-compose.yml)

CREATE TABLE auditoria (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora        TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    usuario_bd        TEXT NOT NULL DEFAULT session_user,
    usuario_app       TEXT,
    operacion         TEXT NOT NULL CHECK (operacion IN ('INSERT','UPDATE','DELETE')),
    esquema           TEXT NOT NULL,
    tabla             TEXT NOT NULL,
    registro_id       TEXT,
    datos_anteriores  JSONB,
    datos_nuevos      JSONB,
    transaccion_id    BIGINT NOT NULL DEFAULT txid_current()
);

CREATE INDEX idx_auditoria_tabla_fecha ON auditoria (tabla, fecha_hora DESC);
CREATE INDEX idx_auditoria_usuario_fecha ON auditoria (usuario_app, fecha_hora DESC);

-- SET search_path fijo (no el de quien llama) para que un caller con
-- privilegios acotados (app_academico) no pueda hacerle "hijacking" al
-- search_path y colar un objeto propio que la funcion resuelva sin
-- querer, dado que corre como SECURITY DEFINER (con los privilegios del
-- owner, no los de app_academico).
CREATE OR REPLACE FUNCTION fn_auditoria()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    anterior   JSONB;
    nuevo      JSONB;
    columna_pk TEXT;
BEGIN
    -- Mecanismo para la futura carga masiva: si esta seteado, no audita
    -- nada (evita ~1 millon de filas de ruido en un solo evento).
    IF current_setting('app.omitir_auditoria', true) = 'true' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    -- Nombre de la columna PK de la tabla, pasado como argumento del
    -- trigger (TG_ARGV[0]) porque no es uniforme entre tablas
    -- (id_usuario, id_tarea, id_entrega, id_calificacion).
    columna_pk := TG_ARGV[0];

    IF TG_OP = 'DELETE' THEN
        anterior := to_jsonb(OLD);
        nuevo    := NULL;
    ELSIF TG_OP = 'INSERT' THEN
        anterior := NULL;
        nuevo    := to_jsonb(NEW);
    ELSE
        anterior := to_jsonb(OLD);
        nuevo    := to_jsonb(NEW);
    END IF;

    -- Nunca guardar el hash de contraseña en el volcado JSONB de usuarios.
    IF TG_TABLE_NAME = 'usuarios' THEN
        anterior := anterior - 'contraseña';
        nuevo    := nuevo - 'contraseña';
    END IF;

    INSERT INTO auditoria (
        usuario_app, operacion, esquema, tabla, registro_id,
        datos_anteriores, datos_nuevos
    ) VALUES (
        NULLIF(current_setting('app.usuario_actual', true), ''),
        TG_OP,
        TG_TABLE_SCHEMA,
        TG_TABLE_NAME,
        COALESCE(nuevo ->> columna_pk, anterior ->> columna_pk),
        anterior,
        nuevo
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Un trigger por tabla, generado dinamicamente porque el nombre de la PK
-- cambia entre tablas (no hay una columna "id" generica como en
-- TrailerSys) -- se resuelve con un CASE dentro del loop y se pasa como
-- argumento del trigger.
DO $$
DECLARE
    tabla      TEXT;
    columna_pk TEXT;
BEGIN
    FOREACH tabla IN ARRAY ARRAY['usuarios', 'tareas', 'entrega', 'calificaciones']
    LOOP
        columna_pk := CASE tabla
            WHEN 'usuarios'       THEN 'id_usuario'
            WHEN 'tareas'         THEN 'id_tarea'
            WHEN 'entrega'        THEN 'id_entrega'
            WHEN 'calificaciones' THEN 'id_calificacion'
        END;

        EXECUTE format('DROP TRIGGER IF EXISTS trg_auditoria ON %I;', tabla);
        EXECUTE format(
            'CREATE TRIGGER trg_auditoria
             AFTER INSERT OR UPDATE OR DELETE ON %I
             FOR EACH ROW EXECUTE FUNCTION fn_auditoria(%L);',
            tabla, columna_pk
        );
    END LOOP;
END $$;

-- app_academico hereda SELECT/INSERT/UPDATE/DELETE automaticamente por
-- el ALTER DEFAULT PRIVILEGES ya existente (db/roles.sql) -- se le quita
-- todo menos INSERT explicitamente. El trigger mismo no depende de esto
-- (corre como postgres via SECURITY DEFINER).
REVOKE SELECT, UPDATE, DELETE ON auditoria FROM app_academico;
